title: Long Haul
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: http://iskandarov.github.io/blog
baseurl: "/blog/"
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Əsas\Blog
   url: /index.html
 - title: Haqqında
   url: /about
 - title: Əlaqə
   url: /contact

social:
   github: iskandarov
   twitter: iskandarovorg
   facebook: mirzaiskandarov
   email: mirzaiskandarov@gmail.com

google_analytics: "UA-58263416-1"
