title: Mirza Iskandarov
description: Programming|Bloging|Science|Books

url: http://iskandarov.org
baseurl: "http://iskandarov.org"
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Əsas\Blog
   url: /index.html
 - title: Haqqında
   url: /about
 - title: Əlaqə
   url: /contact

social:
   github: iskandarov
   twitter: iskandarovorg
   facebook: mirzaiskandarov
   email: mirzaiskandarov@gmail.com

google_analytics: "UA-58263416-1"
