title: Long Haul
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: http://iskandarov.github.io/blog
baseurl: http://iskandarov.github.io/blog/
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: http://iskandarov.github.io/blog/index.html
 - title: About
   url: http://iskandarov.github.io/blog/about
 - title: Contact
   url: http://iskandarov.github.io/blog/contact

social:
   github: iskandarov
   twitter: iskandarovorg
   facebook: brianmaierjr
   email: brimaidesigns@gmail.com

google_analytics: "UA-58263416-1"
